// <auto-generated />
using System;
using AMR.Core.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMR.Core.Infrastructure.Migrations
{
    [DbContext(typeof(AmrCoreDbContext))]
    partial class AmrCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("AMR.Core.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_CLIENTE");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("ST_ATIVO");

                    b.Property<string>("CNPJ")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("NR_CNPJ");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("DS_EMAIL");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_EMPRESA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NM_CLIENTE");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("NR_DOCUMENTO");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("NR_TELEFONE");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT")
                        .HasColumnName("TP_DOCUMENTO");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("CLIENTE", (string)null);
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_EMPRESA");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("ST_ATIVO");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("NR_CNPJ");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("NR_IE");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("NM_FANTASIA");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NM_RAZAO_SOCIAL");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("NR_TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("EMPRESA", (string)null);
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FORNECEDOR");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("ST_ATIVO");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("NR_CNPJ");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("DS_CATEGORIA");

                    b.Property<string>("ContatoResponsavel")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("NM_CONTATO");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("DS_EMAIL");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_EMPRESA");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("NR_IE");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("NM_FANTASIA");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NM_RAZAO_SOCIAL");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("NR_TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("FORNECEDOR", (string)null);
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.ItemPedidoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_ITEM");

                    b.Property<int>("ItemPedidoCompraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoCompraId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PEDIDO_COMPRA");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("VL_PRECO_UNITARIO");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PRODUTO");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("QT_QUANTIDADE");

                    b.HasKey("Id");

                    b.HasIndex("ItemPedidoCompraId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ITEM_PEDIDO_COMPRA", (string)null);
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.ItemPedidoVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_ITEM");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("PC_DESCONTO");

                    b.Property<int>("ItemPedidoVendaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoVendaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PEDIDO_VENDA");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("VL_PRECO_UNITARIO");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PRODUTO");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("QT_QUANTIDADE");

                    b.HasKey("Id");

                    b.HasIndex("ItemPedidoVendaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ITEM_PEDIDO_VENDA", (string)null);
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.MovimentoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_MOVIMENTO");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_MOVIMENTO");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_EMPRESA");

                    b.Property<string>("Origem")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("DS_ORIGEM");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PRODUTO");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("QT_QUANTIDADE");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_TIPO");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("MOVIMENTO_ESTOQUE", (string)null);
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.PedidoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PEDIDO_COMPRA");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_APROVACAO");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_EMISSAO");

                    b.Property<DateTime?>("DataRecebimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_RECEBIMENTO");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_EMPRESA");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_FORNECEDOR");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("DS_OBSERVACAO");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_STATUS");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("PEDIDO_COMPRA", (string)null);
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.PedidoVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PEDIDO_VENDA");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_CLIENTE");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_APROVACAO");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_EMISSAO");

                    b.Property<DateTime?>("DataFaturamento")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_FATURAMENTO");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_EMPRESA");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("DS_OBSERVACAO");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_STATUS");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("PEDIDO_VENDA", (string)null);
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PRODUTO");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("ST_ATIVO");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("DS_PRODUTO");

                    b.Property<decimal>("EstoqueMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("QT_ESTOQUE_MINIMO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NM_PRODUTO");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("VL_PRECO_UNITARIO");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_SKU");

                    b.Property<int>("UnidadeMedidaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_UNIDADE_MEDIDA");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("UnidadeMedidaId");

                    b.ToTable("PRODUTO", (string)null);
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.SaldoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_SALDO");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_EMPRESA");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_PRODUTO");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("QT_SALDO");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId", "EmpresaId")
                        .IsUnique();

                    b.ToTable("SALDO_ESTOQUE", (string)null);
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.UnidadeMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CD_UNIDADE");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("ST_ATIVO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("DS_UNIDADE");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("CD_SIGLA");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("UNIDADE_MEDIDA", (string)null);
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("AMR.Core.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AMR.Core.Domain.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_BAIRRO");

                            b1.Property<string>("CEP")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("TEXT")
                                .HasColumnName("NR_CEP");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_CIDADE");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_COMPLEMENTO");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_ESTADO");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_LOGRADOURO");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("NR_NUMERO");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_PAIS");

                            b1.HasKey("ClienteId");

                            b1.ToTable("CLIENTE");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Empresa");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.Empresa", b =>
                {
                    b.OwnsOne("AMR.Core.Domain.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("EmpresaId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_BAIRRO");

                            b1.Property<string>("CEP")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("TEXT")
                                .HasColumnName("NR_CEP");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_CIDADE");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_COMPLEMENTO");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_ESTADO");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_LOGRADOURO");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("NR_NUMERO");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_PAIS");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("EMPRESA");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.Fornecedor", b =>
                {
                    b.HasOne("AMR.Core.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AMR.Core.Domain.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("FornecedorId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_BAIRRO");

                            b1.Property<string>("CEP")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("TEXT")
                                .HasColumnName("NR_CEP");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_CIDADE");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_COMPLEMENTO");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_ESTADO");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_LOGRADOURO");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("NR_NUMERO");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("DS_PAIS");

                            b1.HasKey("FornecedorId");

                            b1.ToTable("FORNECEDOR");

                            b1.WithOwner()
                                .HasForeignKey("FornecedorId");
                        });

                    b.Navigation("Empresa");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.ItemPedidoCompra", b =>
                {
                    b.HasOne("AMR.Core.Domain.Entities.PedidoCompra", null)
                        .WithMany("Itens")
                        .HasForeignKey("ItemPedidoCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMR.Core.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.ItemPedidoVenda", b =>
                {
                    b.HasOne("AMR.Core.Domain.Entities.PedidoVenda", null)
                        .WithMany("Itens")
                        .HasForeignKey("ItemPedidoVendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMR.Core.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.MovimentoEstoque", b =>
                {
                    b.HasOne("AMR.Core.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.PedidoCompra", b =>
                {
                    b.HasOne("AMR.Core.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.PedidoVenda", b =>
                {
                    b.HasOne("AMR.Core.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.Produto", b =>
                {
                    b.HasOne("AMR.Core.Domain.Entities.UnidadeMedida", "UnidadeMedida")
                        .WithMany()
                        .HasForeignKey("UnidadeMedidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.SaldoEstoque", b =>
                {
                    b.HasOne("AMR.Core.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.PedidoCompra", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("AMR.Core.Domain.Entities.PedidoVenda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
